// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLR_yqjQm3kr5PGWCOzgJz8BaKX6F2vyQ',
    appId: '1:157482539214:web:f40c2949a66ae00c40989f',
    messagingSenderId: '157482539214',
    projectId: 'fir-project-41609',
    authDomain: 'fir-project-41609.firebaseapp.com',
    storageBucket: 'fir-project-41609.appspot.com',
    measurementId: 'G-RR6F7SR0LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWF_MjQHzJbJ5RISxqYNdTRy9XfpXEjtE',
    appId: '1:157482539214:android:543973bb42adac1b40989f',
    messagingSenderId: '157482539214',
    projectId: 'fir-project-41609',
    storageBucket: 'fir-project-41609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGtb0rPYOsvJdcPRopeon2ciq1yO0tOdk',
    appId: '1:157482539214:ios:41f11d1824d2118a40989f',
    messagingSenderId: '157482539214',
    projectId: 'fir-project-41609',
    storageBucket: 'fir-project-41609.appspot.com',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGtb0rPYOsvJdcPRopeon2ciq1yO0tOdk',
    appId: '1:157482539214:ios:41f11d1824d2118a40989f',
    messagingSenderId: '157482539214',
    projectId: 'fir-project-41609',
    storageBucket: 'fir-project-41609.appspot.com',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLR_yqjQm3kr5PGWCOzgJz8BaKX6F2vyQ',
    appId: '1:157482539214:web:065d80c31dbbab2440989f',
    messagingSenderId: '157482539214',
    projectId: 'fir-project-41609',
    authDomain: 'fir-project-41609.firebaseapp.com',
    storageBucket: 'fir-project-41609.appspot.com',
    measurementId: 'G-QLSX1V66QL',
  );
}
